### ISSUE TITLE
refactor: restart project

### ISSUE THREAD

**Issue by RuiFilipeCampos** [Digital-Defiance/typed-api#5]
Delete and redo everything based on the lessons learned from this implementation.

**Comment by BDisp** [comment]
Sometimes is the better choose.

**Comment by RuiFilipeCampos** [comment]
> Sometimes is the better choose.

yes indeed, I've condensed a good chunk of the logic from before to a single, very small module

**Comment by RuiFilipeCampos** [comment]
> > Sometimes is the better choose.
> 
> yes indeed, I've condensed a good chunk of the logic from before to a single, very small module

well not all, it's missing most of the features, but still, it was feeling very over engineered
